version: "3.8"
services:
  php:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: docker-php-server
    restart: always
    ports:
      - 8050:80
    volumes:
      - ./ejercicios:/var/www/html
volumes:
  ejercicios: {}